### PR TITLE
Fixes bug: resolve str function name

### PR DESCRIPTION
**Pull request by MaxFBurg**
in class DataInfoBase -> def make the dataset_fn variable includes a str that needs to be resolved into a callable object.

### CODE REVIEW

**Comment by eywalker** [comment]
Thanks @MaxFBurg  - this totally looks like a Déjà vu - @KonstantinWilleke did we not encounter this issue before and fixed it? Otherwise, how was it that this was working at all?

**Review by KonstantinWilleke — APPROVED** [review]

**Comment by KonstantinWilleke** [comment]
Yes we had this issue before, but I failed to deliver on my promise to fix it. Thank you @MaxFBurg!

**Comment by KonstantinWilleke** [comment]
@MaxFBurg, could you apply black formatting to the PR? then I'd merge it!

**Comment by MaxFBurg** [comment]
> @MaxFBurg, could you apply black formatting to the PR? then I'd merge it!

Great! black formatting done.

**Review by KonstantinWilleke — APPROVED** [review]

**Pull request merged**
