### PR TITLE
Release

### PR DESCRIPTION
**Pull request by mohammadbashiri**

### CODE REVIEW

**Comment by KonstantinWilleke** [comment]
@mohammadbashiri There's a conflict in the `setup.py`.
Could you resolve that one?

**Comment by KonstantinWilleke** [comment]
> > @mohammadbashiri There's a conflict in the `setup.py`. Could you resolve that one?
> 
> I don't get what the conflict is. Do you know how to resolve a conflict for a deleted file? @KonstantinWilleke @cblessing24

I think it's because your release branch is quite far behind the sinzlab master. And also, in his PR to neuralpredictors, Christoph didnt get rid of the setup entirely, but simplified it. I'm not familiar enough with pytoml to understand what that does.

**Comment by mohammadbashiri** [comment]
> > > @mohammadbashiri There's a conflict in the `setup.py`. Could you resolve that one?
> > 
> > 
> > I don't get what the conflict is. Do you know how to resolve a conflict for a deleted file? @KonstantinWilleke @cblessing24
> 
> I think it's because your release branch is quite far behind the sinzlab master. And also, in his PR to neuralpredictors, Christoph didnt get rid of the setup entirely, but simplified it. I'm not familiar enough with pytoml to understand what that does.

I see, will look into it.

**Comment by cblessing24** [comment]
Can you change the `setup.py` to this:
https://github.com/sinzlab/neuralpredictors/blob/87532e14f25407a7cfceee5eae88463ed6c56c4c/setup.py

That is necessary for now to make editable installs work. Otherwise the changes look good.

I am not sure how to resolve the conflict. Easiest might be to create a new branch from `sinzlab/master`, change `pyproject.toml` and `setup.py` and create a new PR.

**Comment by mohammadbashiri** [comment]
The issues are addressed in https://github.com/sinzlab/nnfabrik/pull/141

**Pull request closed without merging**
